import { Plus, Trash2, Pill } from 'lucide-react';
import { Button } from '@/components/ui/button';

const input = 'w-full rounded-lg border border-ayana-line bg-white px-3 py-2 text-sm';
export const MedicineEditor = ({ medicines, onChange, max, prefix, shapes, colors, timings }) => {
  const edit = (i, key, value) => onChange(medicines.map((m, n) => n === i ? { ...m, [key]: value } : m));
  const count = medicines.reduce((n, m) => n + Math.max(1, m.reminder_times?.length || 0), 0);
  return <div className="space-y-4" data-testid={`${prefix}-medicines`}>
    <p className="text-xs text-ayana-secondary" data-testid={`${prefix}-medicine-usage`}>{count} / {max} daily medicine reminders</p>
    {medicines.map((med, i) => <article key={med.id || i} className="rounded-lg border border-ayana-line bg-white p-4 space-y-4" data-testid={`${prefix}-medicine-${i}`}>
      <div className="flex items-center justify-between gap-3"><Pill className="w-5 h-5 text-ayana-primary" /><Button type="button" variant="ghost" size="icon" aria-label={`Remove ${med.name || 'medicine'}`} data-testid={`${prefix}-medicine-remove-${i}`} onClick={() => onChange(medicines.filter((_, n) => n !== i))}><Trash2 className="w-4 h-4" /></Button></div>
      <div className="grid sm:grid-cols-2 gap-4">{[['name', 'Medicine name', 'Name on the label'], ['dose', 'Strength · dose / quantity', '500 mg · 1 tablet']].map(([key, label, placeholder]) => <label key={key} className="text-sm font-medium">{label} *<input required value={med[key] || ''} onChange={e => edit(i, key, e.target.value)} placeholder={placeholder} className={`${input} mt-1`} data-testid={`${prefix}-medicine-${key}-${i}`} /></label>)}</div>
      <div className="grid sm:grid-cols-2 gap-4">{[['shape', 'Shape', shapes], ['color', 'Color', colors]].map(([key, label, values]) => <label key={key} className="text-sm font-medium">{label} *<select required className={`${input} mt-1`} value={med[key] || ''} onChange={e => edit(i, key, e.target.value)} data-testid={`${prefix}-medicine-${key}-${i}`}><option value="">Choose {label.toLowerCase()}</option>{values.map(v => <option key={v.value || v} value={v.value || v}>{v.label || v}</option>)}</select></label>)}</div>
      <div className="flex flex-wrap items-end gap-3">{(med.reminder_times?.length ? med.reminder_times : [med.reminder_time || '09:00']).map((time, j, times) => <label key={j} className="text-sm">Time *<div className="flex gap-1 mt-1"><input type="time" required value={time} className={input} data-testid={`${prefix}-medicine-time-${i}-${j}`} onChange={e => { const next = times.map((t, n) => n === j ? e.target.value : t); onChange(medicines.map((m, n) => n === i ? { ...m, reminder_times: next, reminder_time: next[0] } : m)); }} />{times.length > 1 && <Button type="button" variant="ghost" size="icon" aria-label="Remove time" data-testid={`${prefix}-medicine-remove-time-${i}-${j}`} onClick={() => edit(i, 'reminder_times', times.filter((_, n) => n !== j))}><Trash2 className="w-3 h-3" /></Button>}</div></label>)}<Button type="button" variant="outline" size="sm" disabled={count >= max} data-testid={`${prefix}-medicine-add-time-${i}`} onClick={() => edit(i, 'reminder_times', [...(med.reminder_times?.length ? med.reminder_times : [med.reminder_time || '09:00']), '20:00'])}><Plus className="w-3 h-3 mr-1" />Time</Button></div>
      <label className="block text-sm font-medium">Instructions *<select value={med.timing || ''} onChange={e => edit(i, 'timing', e.target.value)} className={`${input} mt-1`} data-testid={`${prefix}-medicine-instruction-${i}`}><option value="">Choose timing or enter instructions below</option>{timings.map(v => <option value={v.value || v} key={v.value || v}>{v.label || v}</option>)}</select><textarea value={med.notes || ''} onChange={e => edit(i, 'notes', e.target.value)} maxLength={200} className={`${input} mt-2`} placeholder="Instructions from the prescription" data-testid={`${prefix}-medicine-notes-${i}`} /></label>
    </article>)}
    <Button type="button" variant="outline" disabled={count >= max} data-testid={`${prefix}-medicine-add`} onClick={() => onChange([...medicines, { id: crypto.randomUUID(), name: '', dose: '', shape: '', color: '', timing: '', notes: '', reminder_time: '09:00', reminder_times: ['09:00'] }])}><Plus className="w-4 h-4 mr-2" />Add medicine</Button>
  </div>;
};